### ISSUE TITLE
Название коммитов

### ISSUE THREAD

**Issue by aardtempliod** [imakiri/gorum#1]
Желательно придерживаться логически осмысленного названия коммитов.
Даже, если была изменена только одна строчка - либо ждём пока накопятся изменения, либо называем коммиты так же просто "поправил базу", "правки 11.09.2018", "поправил баг в api".

**Comment by imakiri** [comment]
Для этого я создал файл истории коммитов VERSION

**Comment by aardtempliod** [comment]
Большинство других проектов (включая проекты крупных компаний, см. например, https://github.com/google) так не делают.
Поскольку обычно коммит != версия.
Может быть множество коммитов в рамках одной версии, после чего релиз (выпуск новой, например, тестовой версии).
Если тестовая версия значительно отличается от старой (но не только в этом случае), то можно разрабытавать её в отдельной ветке.
Можно разрабатывать в мастере, а стабильные версии выводить в отдельные ветки как тут https://github.com/qt/qt5

**Comment by aardtempliod** [comment]
Также важный момент - в описание коммита можно указывать более одной строчки.
В целом рекомендую посмотреть как оформляют коммиты и релизы в популярных проектах, если цель - научиться.
Если проект чисто для себя и показывать его код никому не собираетесь - можно оформлять всё как угодно, но если цель использования гита - научиться коммандному взаимодействию, то лучше делать как все привыкли.

**Comment by imakiri** [comment]
> если цель использования гита - научиться коммандному взаимодействию, то лучше делать как все привыкли

Цель истользования гита - контроль версий. Для того чтобы учиться командному взаимодействию нужно быть в команде, а я "работаю" тут в соло. 

> Поскольку обычно коммит != версия.
> Может быть множество коммитов в рамках одной версии, после чего релиз (выпуск новой, например, тестовой версии).

У меня тут иначе. Каждый коммит есть версия. Некоторые версии становятся релизными. Теоретически можно прикрутить релизное версионирование. Но у меня была только 1 релизная версия - C23, так что рано ещё.
