### ISSUE TITLE
Хранение настроек

### ISSUE THREAD

**Issue by aardtempliod** [imakiri/gorum#2]
Хранить настройки в отдельных файлах - не самый современный подход.
Желательно хранить настройки либо в одном файле (например в формате json или xml, так пользователи смогут комментировать и подписывать настройки) или в переменных окружения.
Тогда запуск софта с настройками будет каким-то таким:
PORT=80 API_KEY=asdasdasd BASE=localhost:3630 BASE_U=user BASE_P=pass ./my_go_server
Также есть такое понятие как ENV-файлы для упрощения развёртывания приложения под Linux.

**Comment by imakiri** [comment]
Это временное решение чтобы не отвлекаться от основной задачи и не светить приватными данными на гите

**Comment by aardtempliod** [comment]
понятно. Я пишу как обычно это делается, а не как должно быть прямо сейчас.
Так вот, обычно делают 2 файла -  один что-то вроде config_template.conf - в котором настройки по умолчанию БЕЗ ключей,
и второй - собственно config.conf который в gitignore (или вообще лежит вне пределов репозитория, например, в /etc или C:\Program Files\MyCoolApp\config.conf).
Так достигается безопасность конфигов И их единство, поскольку шаблон (он же файл по умолчанию) может содержать пояснения и закомментированииые части.
