### ISSUE TITLE
Кое ЧТО здесь происходит?

### ISSUE THREAD

**Issue by aardtempliod** [imakiri/gorum#3]
Можете также вкратце описать в README что в итоге будет делать проект (можно в форме TODO) или как-то ещё?
Обычно хорошей практикой является хотя-бы примерное представление / дизайн (в смысле не внешний вид, а проработка структуры приложения/таблиц, например) перед началом разработки.

В компаниях, где разработку ПО заказывают другие компании вместо этого применяется ТЗ (техническое задание), в котором заказчик (не всегда точно и правильно, к сожалению) описывает, как должен выглядеть и что делать продукт.

В случае с опенсорсом, автор разрабатывает продукт как хочет, но обычно к тому моменту как публикуется репозиторий хоть краткое описание но имеется.

Например, на том же https://github.com/google/llvm-bazel есть краткое описание в первом же коммите. Плюс так будет более ясно что мне тут смотреть. Т.к. в проекте много разных файлов и модулей, не всегда понятно где и что должно делать.

**Comment by imakiri** [comment]
> Обычно хорошей практикой является хотя-бы примерное представление / дизайн (в смысле не внешний вид, а проработка структуры приложения/таблиц, например) перед началом разработки

Я целый месяц этим и занимаюсь - пытаясь понять что где как должно лежать и как друг с другом должно соединяться. Первичная схема бд лежит в data/schema.sql
