### ISSUE TITLE
Gorilla Mux

### ISSUE THREAD

**Issue by aardtempliod** [imakiri/gorum#4]
На мой взгляд конфигурацию route-ов можно собрать в один пакет.
Да, можно разнести по разным файлам, но по разным пакетам - это на мой взгляд перебор.

У нас в проектах редирект на https и раздача статики идёт через nginx, который стоит перед бэкэндом, но для обучения можно и тут сделать.

Сам редирект можно сделать компактнее:
```
go http.ListenAndServe(":80", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    http.Redirect(w, r, "https://"+r.Host+r.URL.String(), http.StatusMovedPermanently)
}))
```
Не обязательно его размазывать по файлу.

Для раздачи статики - не обязательно создавать по хендлеру на каждый файл.
Есть такая штука:
`http.Handle("/", http.FileServer(http.Dir("./static")))`
Она должна уже быть с защитой от побега через ../../..

**Comment by imakiri** [comment]
> http.Handle("/", http.FileServer(http.Dir("./static")))

Такое работать не будет(раздача css файлов, проверял в С13) Но я сейчас получше погуглил, и нашёл рабочее решение.

> Она должна уже быть с защитой от побега через ../../..

Не очень понимаю что это.

> Также упомяну (на будущее), что есть такая тема, как VFS (типа "виртуальная файловая система") - это пакет, который 
> позволяет встроить все статические файлы в бинарник сервера. Увеличивает размер файла, но упрощает развёртывание - нужен только один ELF/EXE и конфиг.
> Если бинарник запускается на удалённом сервере, то становится удобнее разворачивать.

Чем плохи
```
git clone github.com/...
go build main.go
```
на целевом сервере?

**Comment by imakiri** [comment]
> http.Handle("/", http.FileServer(http.Dir("./static")))

Такое работать не будет(раздача css файлов, mux.Router, проверял в С13) Но я сейчас получше погуглил, и нашёл рабочее решение.

> Она должна уже быть с защитой от побега через ../../..

Не очень понимаю что это.

> Также упомяну (на будущее), что есть такая тема, как VFS (типа "виртуальная файловая система") - это пакет, который 
> позволяет встроить все статические файлы в бинарник сервера. Увеличивает размер файла, но упрощает развёртывание - нужен только один ELF/EXE и конфиг.
> Если бинарник запускается на удалённом сервере, то становится удобнее разворачивать.

Чем плохи
```
git clone github.com/...
go build main.go
```
на целевом сервере?

**Comment by imakiri** [comment]
> http.Handle("/", http.FileServer(http.Dir("./static")))

Такое работать не будет(через mux.Router, проверял в С13) Но я сейчас получше погуглил, и [нашёл ](https://stackoverflow.com/questions/21234639/golang-gorilla-mux-with-http-fileserver-returning-404)рабочее решение.

> Она должна уже быть с защитой от побега через ../../..

Не очень понимаю что это.

> Также упомяну (на будущее), что есть такая тема, как VFS (типа "виртуальная файловая система") - это пакет, который 
> позволяет встроить все статические файлы в бинарник сервера. Увеличивает размер файла, но упрощает развёртывание - нужен только один ELF/EXE и конфиг.
> Если бинарник запускается на удалённом сервере, то становится удобнее разворачивать.

Чем плохи
```
git clone github.com/...
go build main.go
```
на целевом сервере?
